spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive
  config:
    import: configserver:http://localhost:8888

  profiles:
    active: dev

server:
  port: 8080