spring:
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888
