server:
  port: 8085
spring:
  application:
    name: show-service

  config:
    import: configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/show_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: dev

