app: user-service
custom:
    message: "Hello from User Service!!"
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update