server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/NagarajuKuruba/moviebazaar-platform.git
          search-paths:
            - config-repo/common
            - config-repo/{profile}
          default-label: develop
          clone-on-start: true